language: node_js
node_js:
  - 9
cache:
  directories:
  - global-cli/node_modules
  - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
      branch: master